website/internal/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'internal'
urlpatterns = [
    url(r'^$', auth_views.login, {'template_name': 'internal/login.html'}, name='login'),
    url(r'^events/$', views.event_list, name='event_list'),
    url(r'^members/$', views.member_list, name='member_list'),
    url(r'^register/$', views.register, name='register'),
    url(r'^events/(?P<event_name>.+)/$', views.event_details, name='event_details'),
    url(r'^members/(?P<username>.+)/$', views.member_details, name='member_details'),
    url(r'^committees/$', views.committees, name='committees'),
    url(r'^committees/(?P<name>.+)/$', views.committee_members, name='committee_members')
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^internal/', include('internal.urls')),
    url(r'^admin/', admin.site.urls),
]

website/events/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser

class Event(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    title = models.TextField()
    description = models.TextField()
    time = models.DateTimeField()
    speaker_first_name = models.CharField(max_length=100)
    speaker_last_name = models.CharField(max_length=100)
    projected_attendance = models.IntegerField()
    venue = models.TextField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)

    # link fields
    facebook_link = models.CharField(max_length=300)
    eventbrite_link = models.CharField(max_length=300)
    elf_link = models.CharField(max_length=300)
    elf_exemption_link = models.CharField(max_length=300)
    fbcover_link = models.CharField(max_length=300)
    websitephoto_link = models.CharField(max_length=300)
    seal_link = models.CharField(max_length=300)

    def get_speaker_name(self):
        return '%s %s' % (speaker_first_name, speaker_last_name)

semester_validator = RegexValidator(r'(fa|sp)20[0-9][0-9]')

class Member(AbstractUser):
    semester_joined = models.CharField([semester_validator], max_length=6)
    status = models.IntegerField()
    bio = models.TextField()
    attendance = models.DecimalField(max_digits=5, decimal_places=2)

    def get_status(self):
        if self.status == 0:
            return 'active'
        elif self.status == 1:
            return 'first semester associate'
        elif self.status == 2:
            return 'second semester associate'
        else:
            return 'alumni'

class Group(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    friendly_name = models.CharField(max_length=200)

class Committee(Group):
    members = models.ManyToManyField(Member, related_name='committees')
    vp = models.ForeignKey(Member, on_delete=models.CASCADE)

class SubCommittee(Group):
    parent_committee = models.ForeignKey(Committee, on_delete=models.CASCADE,
                                  related_name='subcommittees')
    members = models.ManyToManyField(Member, related_name='subcommittees')
    project_manager = models.ForeignKey(Member, on_delete=models.CASCADE)

class Division(Group):
    members = models.ManyToManyField(Member, related_name='divisions')
    director = models.ForeignKey(Member, on_delete=models.CASCADE)

website/internal/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser

semester_validator = RegexValidator(r'(fa|sp)20[0-9][0-9]')

class Member(AbstractUser):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('associate_first', 'First Semester Associate'),
        ('associate_second', 'Second Semester Associate'),
        ('alumni', 'Alumni'),
    )
    # name = models.CharField(max_length=200, unique=False, null=True, default=None)
    semester_joined = models.CharField([semester_validator], max_length=6, blank=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES)
    bio = models.TextField(blank=True)
    attendance = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    title = models.TextField(default='General Member')


    # contact/social info
    cell_phone = models.CharField(max_length=11, blank=True)
    facebook = models.CharField(max_length=300, blank=True)
    instagram = models.CharField(max_length=300, blank=True)
    snapchat = models.CharField(max_length=300, blank=True)

    @property
    def isActive(self):
        return self.status == ('active')

    def __unicode__(self):
        return u'%s' % self.username

class Event(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    title = models.TextField()
    description = models.TextField()
    time = models.DateTimeField()
    speaker_first_name = models.CharField(max_length=100)
    speaker_last_name = models.CharField(max_length=100)
    speaker_bio = models.TextField()
    projected_attendance = models.IntegerField()
    venue = models.TextField(default='TBD')
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_by = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='created_events')
    point_person = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='pp_events')
    confirmed = models.BooleanField(default=False)
    # complete = models.BooleanField(default=False)

    # link fields
    facebook_link = models.CharField(max_length=300, blank=True)
    eventbrite_link = models.CharField(max_length=300, blank=True)
    elf_link = models.CharField(max_length=300, blank=True)
    elf_exemption_link = models.CharField(max_length=300, blank=True)
    fbcover_link = models.CharField(max_length=300, blank=True)
    website_photo_link = models.CharField(max_length=300, blank=True)
    seal_link = models.CharField(max_length=300, blank=True)

    @property
    def speaker_full_name(self):
        return u'%s %s' % (self.speaker_first_name, self.speaker_last_name)

    def __unicode__(self):
        return u'%s' % self.name

class Group(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    friendly_name = models.CharField(max_length=200)

    def __unicode__(self):
        return u'%s' % self.name

class Committee(Group):
    members = models.ManyToManyField(Member, related_name='committees')
    vp = models.ForeignKey(Member, on_delete=models.CASCADE)

class SubCommittee(Group):

    parent_committee = models.ForeignKey(Committee, on_delete=models.CASCADE,
                                  related_name='subcommittees')
    members = models.ManyToManyField(Member, related_name='subcommittees')
    project_manager = models.ForeignKey(Member, on_delete=models.CASCADE)

class Division(Group):
    members = models.ManyToManyField(Member, related_name='divisions')
    director = models.ForeignKey(Member, on_delete=models.CASCADE)

website/events/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the events index.")

website/internal/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Event
from .models import Member
from .models import Committee

def event_list(request):
    lst = Event.objects.all().order_by('name')
    context = {'event_list': lst}
    return render(request, 'internal/event_list.html', context)

def event_details(request, event_name):
	event = Event.objects.get(name=event_name)
	context = {'event': event}
	return render(request, 'internal/event_details.html', context)

def register(request):
    return HttpResponse("You're trying to register")

def member_list(request):
    lst = Member.objects.all()
    context = {'member_list': lst}
    return render(request, 'internal/member_list.html', context)

def member_details(request, username):
    member = Member.objects.get(username=username)
    context = {'member': member}
    return render(request, 'internal/member_details.html', context)

def committees(request):
    lst = Committee.objects.all()
    context = {'committees': lst}
    return render(request, 'internal/committees.html', context)

def committee_members(request, name):
    comm = Committee.objects.get(name = name)
    print(comm)
    lst = Member.objects.filter(committees__in=[comm])
    print(lst)
    context = {'members': lst}
    return render(request, 'internal/committee_members.html', context)

website/internal/templates/internal/base.html
<!DOCTYPE html>
{% load static %}
{% load tags %}

{% url 'internal:event_list' as event_list_url %}
{% url 'internal:member_list' as member_list_url %}
{% url 'internal:committees' as committees_url %}

<html>
    <head>
		<meta charset="utf-8">
		<title>
			The Berkeley Forum - {% block title %}{% endblock %}
		</title>
		<link rel="stylesheet" type="text/css" href="{% static 'internal/css/style.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="{% static 'internal/js/main.js' %}"></script>
	</head>
	<body>
		<div id="navbar" style="{% block nav-visibility %}{% endblock %}">
			<h5 class='navbar-header'>THE BERKELEY FORUM</h5>
			<a class="{% active request event_list_url %}" href="{{ event_list_url }}">Events</a>
			<a class="{% active request member_list_url %}" href="{{ member_list_url }}">Directory</a>
			<a class="{% active request committees_url %}" href="{{ committees_url }}">Committee</a>
		</div>
		<div id="container">
			{% block pagecontent %}
			{% endblock %}
		</div>
	</body>
</html>

website/internal/templates/internal/committee_members.html
{% extends 'internal/base.html' %}

{% block title %}Committee members{% endblock %}

{% block pagecontent %}
	<div class="content">
		<table class="list-table">
            {% for member in members %}
                {% if member.isActive %}
						<tr class='row'>
							<td class='half-row'>{{member.first_name}} {{member.last_name}}</td>
							<td class='half-row'>{{ member.title}}</td>

						</tr>
					{% endif %}
            {% endfor %}
        </table>
	</div>
{% endblock %}

website/internal/templates/internal/committees.html
<!DOCTYPE html>
{% extends 'internal/base.html' %}
{% url 'internal:committees' as committees_url %}

{% block title %}Committees{% endblock %}

{% block pagecontent %}
	<div class="content">
		<table class="list-table">
			<tr class="header-row">

				<th class='long-col'>Committees</th>

			</tr>
			{% if committees %}
				{% for committee in committees %}

					<tr class='event-row' data-url='{{ committees_url }}{{ committee.name }}'>

						<td class="row">{{committee.name}}</td>


					</tr>

				{% endfor %}
			{% else %}
				<p>No Members to Display</p>
			{% endif %}
		</table>
	</div>
{% endblock %}

website/internal/templates/internal/event_details.html
{% extends 'internal/base.html' %}

{% block title %}{{ event.title }}{% endblock %}

{% block pagecontent %}
 	<div class='content'>
 		<div>
 			<h3>Event name is {{ event.title }}.</h3>
 		</div>
 	</div>
 {% endblock %}     

website/internal/templates/internal/event_list.html
<!DOCTYPE html>
{% extends 'internal/base.html' %}
{% url 'internal:event_list' as event_list_url %}

{% block title %}Events{% endblock %}

{% block pagecontent %}
	<div class="content">
		<table class="list-table">
			<tr class="header-row">
				<th class='status-col'>Status</th>
				<th class='long-col'>Event Title</th>
				<th class='short-col'>Speaker</th>
				<th class='short-col'>Date</th>
			</tr>
			{% if event_list %}
				{% for event in event_list %}
					<tr class='event-row' data-url='{{ event_list_url }}{{ event.name }}'>
						{% if event.confirmed %}
							<td class='status-confirmed'>&middot;</td>
						{% else %}
							<td class='status-not-confirmed'>&middot;</td>
						{% endif %}
						<td class='half-row'>{{ event.title }}</td>
						<td class='quarter-row'>{{ event.speaker_full_name }}</td>
						<td class='quarter-row'>{{ event.time }}</td>
					</tr>
				{% endfor %}
			{% else %}
				<p>No events available.</p>
			{% endif %}
	</div>
{% endblock %}

website/internal/templates/internal/login.html
<!DOCTYPE html>
{% extends 'internal/base.html' %}

{% block title %}Log In{% endblock %}
{% block nav-visibility %}display: none{% endblock %}

{% block pagecontent %}
	<div class="absolute-center">
		<h1>THE BERKELEY FORUM</h1>

		<form id="login-form" method="post" action="{% url 'internal:login' %}">
			{% csrf_token %}
			<input name="username" type="text" class="text-field" placeholder="Username">
			<input name="password" type="password" class="text-field" placeholder="Password">
			<input type="submit" value="LOG IN" id="login-button">
			<input type="hidden" name="next" value="{{ next }}">
		</form>

		{% if form.errors %}
			<p class="error-message"> Your username and password didn't match. Please try again.</p>
		{% endif %}
	</div>
{% endblock %}

website/internal/templates/internal/member_details.html
{% extends 'internal/base.html' %}

{% block title %}{{member.first_name}} {{member.last_name}}{% endblock %}

{% block pagecontent %}
 	<div class='content'>
 		<div>
            <h3> {{member.first_name}} {{member.last_name}}</h3>
 			<h3> {{ member.bio }}</h3>
 		</div>
 	</div>
 {% endblock %}

website/internal/templates/internal/member_list.html
<!DOCTYPE html>
{% extends 'internal/base.html' %}
{% url 'internal:member_list' as member_list_url %}

{% block title %}Members{% endblock %}

{% block pagecontent %}
	<div class="content">
		<table class="list-table">
			<tr class="header-row">

				<th class='med-col'>Name</th>
				<th class='med-col'>Role</th>
			</tr>
			{% if member_list %}
				{% for member in member_list %}
					{% if member.isActive %}
						<tr class='event-row' data-url='{{ member_list_url }}{{ member.username }}'>

							<td class='half-row'>{{member.first_name}} {{member.last_name}}</td>
							<td class='half-row'>{{ member.title}}</td>

						</tr>
					{% endif %}
				{% endfor %}
			{% else %}
				<p>No Members to Display</p>
			{% endif %}
		</table>
	</div>
{% endblock %}